### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by blackdiamondsoftware** [xqq/mpegts.js#76]
Followed your instructions in the readme, the json file in the root dir does not have a build script so it fails. 

when i move to the mpedgts.js  folder and try a build there it also fails  re webpack missing witch i installed in the base dir and the mpegts.js dir

not sure what im doing wrong with this project as i have any no issues building others

**Comment by blackdiamondsoftware** [comment]
10% building 0/1 modules 1 active ...map-loader\index.js!C:\Users\andrew\mpegts\src\index.jsC:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\andrew\mpegts\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\andrew\mpegts\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\andrew\mpegts\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\andrew\mpegts\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\andrew\mpegts\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (C:\Users\andrew\mpegts\node_modules\ts-loader\dist\index.js:88:5)
    at successLoader (C:\Users\andrew\mpegts\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\Users\andrew\mpegts\node_modules\ts-loader\dist\index.js:22:12)
    at LOADER_EXECUTION (C:\Users\andrew\mpegts\node_modules\loader-runner\lib\LoaderRunner.js:119:14) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by fegauthier** [comment]
I had the same error while.compiling on Windows. I used Linux Ubuntu instead and it worked.
